export default function Home() {
  return (
    <main className={'border-dividing ml-24 min-h-96 border-l pl-16'}>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
      <p>Hi</p>
    </main>
  )
}
